name: test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        compiler: [gcc]

    steps:
      - name: install
        run: sudo apt install ccache tidy

      - name: checkout reference
        uses: actions/checkout@v2
        with:
          path: core
      - name: checkout test data
        uses: actions/checkout@v2
        with:
          repository: opendocument-app/OpenDocument.test
          token: ${{ secrets.ACCESS_TOKEN }}
          path: test

      - name: ccache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-rev1

      - name: build
        run: |
          mkdir -p core/build
          cd core/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j4
          sudo cmake --build . --target install

      - name: meta
        run: |
          mkdir -p output/meta
          python3 -u core/scripts/meta.py meta output/meta test/od?/* test/???x/* test/doc/* test/ppt/* test/xls/*
      - name: html
        run: |
          mkdir -p output/html
          python3 -u core/scripts/translate.py translate output/html test/od?/* test/???x/*
      - name: tidy
        run: python3 -u core/scripts/tidy.py "tidy -ashtml -utf8 -eq" output/html/*
      - name: render
        run: |
          mkdir -p output/image
          python3 -u core/scripts/render.py "phantomjs core/scripts/render.js" output/image output/html/*
